fix(acp): add checkpoint_enabled to _ACPSessionProxy
_ACPSessionProxy is used by ACPProtocolHandler when creating
ACPInputProvider for elicitation. Without checkpoint_enabled,
ACPInputProvider.supports_durable_elicitation raises
AttributeError: '_ACPSessionProxy' object has no attribute
'checkpoint_enabled'.

Refs: https://github.com/Leoyzen/agentpool/issues/107